[project]
name = "comfyui-montagen"
description = "ComfyUI Video Studio with Node-Controlled Timelines for Multi-Task Production."
version = "0.2.1"
license = {file = "LICENSE"}
dependencies = ["smbprotocol","ffmpeg-binaries"]

[project.urls]
Repository = "https://github.com/MontagenAI/ComfyUI-Montagen"


[tool.comfy]
PublisherId = "montagenai"
DisplayName = "ComfyUI-Montagen"
Icon = ""
