[project]
name = "comfyui-montagen"
description = "A built-in video editor for ComfyUI, integrating media clips with custom nodes, and enabling AI-driven video generation and automation."
version = "0.1.2"
license = {file = "LICENSE"}
dependencies = ["moviepy"]

[project.urls]
Repository = "https://github.com/MontagenAI/ComfyUI-Montagen"


[tool.comfy]
PublisherId = "montagenai"
DisplayName = "ComfyUI-Montagen"
Icon = ""
